:Author: Wade Berrier

audiobook_tool README
=====================

History
--------
I took a job where I was driving 100 miles every day.  The audiobook became my
new best friend.

A quick google search showed that there weren't any nice linux tools to create
audiobooks, so I started hacking some scripts together.  They were hacky, but
I only had to use them every few weeks when I wanted a new audiobook.

After listening to dozens of books, I started collecting a list of features
that I wanted my authored books to have.

An audiobook-interested coworker knew how to create chapters for mp4 books,
and I started adding scripts to get chapter goodness.

There were a mess of scripts and really they were only useful to me.  I had
different scripts for making books from cds, mp3s, etc, and I eventually
combined them into an encompassing tool to make them easier to use.  This way
I didn't have to re-learn my hacky scripts every time I used them.

Through more and more usage as well as input from the previously mentioned
coworker, the tool evolved to something useful for at least one other person.

This other person (we may as well identify him: Joel) started adding cool
features so I eventually posted the code to ease collaboration.

