#!/usr/bin/env python3

import re
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("bottom", type=float, nargs='?', default=2.0,
                    help="minimum gap size")
parser.add_argument("top",    type=float, nargs='?', default=float('inf'),
                    help="maximum gap size")
parser.add_argument("--format", required=False, choices=['m4b', 'mka', 'ogg', 'opus'], default="m4b",
                    help="Chapter format to use")
args = parser.parse_args()

count = 0

for line in sys.stdin:
    matches = re.search(r"^(\d+)\t(\d+)\t(\d+)\.(\d+)$", line.rstrip())

    if matches:
        (gap, chap, s, ms) = (int(matches.group(1)), int(matches.group(2)), int(matches.group(3)), int(matches.group(4)))

        gap_s = float(gap) / 1000

        if args.bottom <= gap_s and gap_s <= args.top:
            count = count + 1

            time_str = "%02d:%02d:%02d.%03d" % (s//3600, (s//60) % 60, s % 60, ms//10)

            if args.format == "m4b":  # m4b format
                print("%s Chapter %s (silence %s)" % (time_str, chap, gap))
            else:  # ogg/opus/mka format
                print("CHAPTER%03d=%s" % (count, time_str))
                print("CHAPTER%03dNAME=Chapter %s (silence %s)" % (count, chap, gap))
